### ISSUE TITLE
[sapl-editor-for-vaadin] CodeMirror in Sapl-Editor component not shown in Vaadin production builds

### ISSUE THREAD

**Issue by nniikkoollaaii** [heutelbeck/sapl-server#3]
Starting the sapl-demo-web-editor demo in vaadin production mode via
`mvn spring-boot:run -P production`
and navigating to localhost:8080 the CodeMirror component is not shown.

![image](https://user-images.githubusercontent.com/35990414/120232491-f1d0d000-c253-11eb-9d4d-ce13a5a2e0aa.png)

The HTML DOM contains the <sapl-editor> tag and it's shadow root. But below this the CodeMirror elements are missing:

![sapl-editor-prod-mode-html-dom](https://user-images.githubusercontent.com/35990414/120233031-2002df80-c255-11eb-9e92-438f4f16388c.png)

This seems to be caused by an invalid Javascript generated after Vaadin production mode treeshaking because the following errors are written to the JavaScript console:

![image](https://user-images.githubusercontent.com/35990414/120232717-673ca080-c254-11eb-8817-3f08f55fb9b0.png)

@Nipahu please check how you're including the CodeMirror / Xtext JS dependencies and how to correctly do this for vaadin production mode.

cc @pengelberts @heutelbeck

**Comment by pengelberts** [comment]
@nniikkoollaaii 
Temporary workaround: Set the "optimizeBundle" parameter of the "build-frontend" Vaadin Maven goal to false.
Example: https://github.com/heutelbeck/sapl-server/blob/main/sapl-server-ce/pom.xml#L305

@Nipahu 
The cause of the bug relates to the production optimization executed during the "build-frontend" goal.

**Comment by Nipahu** [comment]
@pengelberts 
Thanks for reminding me of that workaround.

@nniikkoollaaii 
I added this workaround while I'm looking into this so you shouldn't have an issue to run the editor in production mode for now. Can you try it and get back to me?

**Comment by nniikkoollaaii** [comment]
I can confirm that the suggested workaround is working.

One difference: I had to add the "optimizeBundle" parameter on the **"prepare-frontend"** goal. 
https://github.com/heutelbeck/sapl-demos/blob/45f80d6ce70637373d20a4a2181a60b47b6ed663/sapl-demo-playground/pom.xml#L209 
Only then the sapl-editor components are shown when running vaadin in production mode.
